version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: mern-api
    env_file: server/.env
    ports:
      - "5000:5000"
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: mern-web
    ports:
      - "3000:80"
    depends_on:
      - api
    restart: always

  mongo:
    image: mongo:6
    container_name: mern-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data: {}